[workspace]
members = ["crates/wars", "crates/wars-rt", "crates/waffle-func-reloop"]
resolver = "3"

[workspace.package]
license = "CC0-1.0"
description = "Wasm to Rust converter"

[workspace.dependencies]
waffle = { package = "portal-pc-waffle", version = "^0.5.5" }
