//! Known-failures manifest: parse, write, and enforce expectations.

use anyhow::{bail, Context, Result};
use serde::{Deserialize, Serialize};
use std::collections::BTreeSet;
use std::path::Path;

/// One manifest entry: a known-failing command.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord)]
pub struct Entry {
    pub file: String,
    /// Command index within the file (0-based, in script order).
    pub idx: usize,
    pub backend: String,
    pub reason: String,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct Manifest {
    pub entries: BTreeSet<Entry>,
}

impl Manifest {
    pub fn load(path: &Path) -> Result<Manifest> {
        if !path.exists() {
            return Ok(Manifest::default());
        }
        let text = std::fs::read_to_string(path)
            .with_context(|| format!("reading manifest {}", path.display()))?;
        #[derive(Deserialize)]
        struct ManifestFile {
            #[serde(rename = "entry", default)]
            entry: Vec<Entry>,
        }
        let parsed: ManifestFile = toml::from_str(&text)
            .with_context(|| format!("parsing manifest {}", path.display()))?;
        Ok(Manifest {
            entries: parsed.entry.into_iter().collect(),
        })
    }

    /// Write the manifest as a TOML array-of-tables.
    pub fn save(&self, path: &Path) -> Result<()> {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let mut out = String::new();
        out.push_str("# Known-failures manifest for the wars2 spectest harness.\n");
        out.push_str("# Generated by `spectests --write-manifest`. Edit reasons freely;\n");
        out.push_str("# `--check` fails on entries that now pass (stale) and on failures\n");
        out.push_str("# absent from this list (unexpected).\n\n");
        for e in &self.entries {
            out.push_str(&format!(
                "[[entry]]\nfile = \"{}\"\nidx = {}\nbackend = \"{}\"\nreason = \"{}\"\n\n",
                e.file, e.idx, e.backend, e.reason.replace('"', "'")
            ));
        }
        std::fs::write(path, out)?;
        Ok(())
    }

    /// Build a manifest covering every current failure in the report.
    pub fn from_report_failures(report: &crate::report::Report) -> Manifest {
        let mut entries = BTreeSet::new();
        for f in &report.files {
            for c in &f.cases {
                if let crate::report::Outcome::Fail { msg } = &c.outcome {
                    entries.insert(Entry {
                        file: f.file.clone(),
                        idx: c.index,
                        backend: f.backend.clone(),
                        reason: format!("{:.140}", msg),
                    });
                }
            }
        }
        Manifest { entries }
    }

    /// Check a report against expectations. Returns error text on violation.
    /// Matching is keyed on (file, idx, backend) only — `reason` is free-form.
    pub fn check(&self, report: &crate::report::Report) -> Result<()> {
        use std::collections::{HashMap, HashSet};
        let mut expected: HashSet<(String, usize, String)> = HashSet::new();
        let mut reasons: HashMap<(String, usize, String), String> = HashMap::new();
        for e in &self.entries {
            let k = (e.file.clone(), e.idx, e.backend.clone());
            expected.insert(k.clone());
            reasons.entry(k).or_insert_with(|| e.reason.clone());
        }

        let mut unexpected = vec![];
        let mut stale = expected.clone();

        for f in &report.files {
            for c in &f.cases {
                match &c.outcome {
                    crate::report::Outcome::Fail { msg } => {
                        let k = (f.file.clone(), c.index, f.backend.clone());
                        if expected.contains(&k) {
                            stale.remove(&k);
                        } else {
                            unexpected.push(format!(
                                "  {} [{}] cmd {} (line {}): {}",
                                f.file, f.backend, c.index, c.line, msg
                            ));
                        }
                    }
                    _ => {}
                }
            }
        }

        if !unexpected.is_empty() {
            bail!(
                "{} unexpected failure(s):\n{}",
                unexpected.len(),
                unexpected.iter().take(30).cloned().collect::<Vec<_>>().join("\n")
            );
        }
        if !stale.is_empty() {
            bail!(
                "{} stale manifest entrie(s) (now passing) — remove them:\n{}",
                stale.len(),
                stale.iter().take(30).map(|(f, i, b)| format!("  {} [{}] cmd {}", f, b, i)).collect::<Vec<_>>().join("\n")
            );
        }
        Ok(())
    }
}
