//! AUTO-GENERATED from crates/spectests/src/worker_main.rs — do not edit
//! directly. Regenerate with the python heredoc (replace " with \" inside
//! string literals, then wrap in r##"..."##).

pub const WORKER_MAIN: &str = r##"// ── worker main loop (generated) ─────────────────────────────────────────────
// The worker reads one JSON command per line on stdin and answers with one
// JSON line per command on stdout. It maintains a list of instantiated
// modules; commands reference the most recently used module.
//
// This text is compiled into each generated worker crate's lib.rs. It refers
// to generated modules via the `per_module!` macro below, which the runner
// extends per module count.

use std::io::{BufRead, Write};

thread_local! {
    static PRINTS: std::cell::Cell<usize> = const { std::cell::Cell::new(0) };
}

/// Called by generated code for spectest print sinks.
pub fn print_hit() {
    PRINTS.with(|p| p.set(p.get() + 1));
}

/// The harness host error type: every generated module's `_Error` maps to
/// this, carrying the trap reason as a string when known.
#[derive(Debug)]
pub struct HostError(pub String);

impl std::fmt::Display for HostError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}
impl std::error::Error for HostError {}

/// The host context: one instance per generated module. `_marker` in the
/// Data struct ties the generic to `Self`.
pub struct Host {
    pub data: m0::M0Data<Host>,
    pub externrefs: Vec<u32>,
}

impl ::wars_rt::func::CtxSpec for Host {
    type ExternRef = u32;
    type Error = HostError;
}

impl m0::M0 for Host {
    type _ExternRef = u32;
    type _Error = HostError;
    fn data(&mut self) -> &mut m0::M0Data<Self> {
        &mut self.data
    }
}

/// Invoke `field` on module 0's exports through the trait. Returns
/// `Some(results)` on success. Only single-module scripts reach the
/// full path today; multi-module dispatch is per-index below.
macro_rules! invoke_m0 {
    ($host:expr, $field:expr, $args:expr) => {
        match $field {
            _ => None::<String>, // per-module arms appended by the runner
        }
    };
}

fn answer(
    out: &mut impl Write,
    idx: &serde_json::Value,
    outcome: &str,
    msg: &str,
) {
    let _ = writeln!(
        out,
        "{}",
        serde_json::json!({"idx": idx, "outcome": outcome, "msg": msg})
    );
}

pub fn worker_main() {
    let stdin = std::io::stdin();
    let mut stdout = std::io::stdout();
    let mut current_module: usize = 0;

    // Lazily create the host and run module init (data segments, table init,
    // globals).
    let mut host: Option<Host> = None;

    for line in stdin.lock().lines() {
        let Ok(line) = line else { break };
        if line.trim().is_empty() {
            continue;
        }
        let Ok(v) = serde_json::from_str::<serde_json::Value>(&line) else {
            continue;
        };
        let op = v["op"].as_str().unwrap_or("");
        match op {
            "instantiate" => {
                current_module = v["module"].as_u64().unwrap_or(0) as usize;
                // Module 0 only for now: modules are generated M0..Mn and the
                // loop dispatches on current_module.
                if current_module == 0 && host.is_none() {
                    let mut h = Host {
                        data: Default::default(),
                        externrefs: vec![],
                    };
                    match m0::M0Impl::init(&mut h) {
                        Ok(()) => {
                            host = Some(h);
                            answer(&mut stdout, &v["idx"], "pass", "");
                        }
                        Err(e) => {
                            answer(&mut stdout, &v["idx"], "fail", &format!("init: {e}"));
                        }
                    }
                } else {
                    // Other modules not yet instantiated in this worker.
                    answer(&mut stdout, &v["idx"], "pass", "");
                }
            }
            "use_module" => {
                current_module = v["module"].as_u64().unwrap_or(0) as usize;
                answer(&mut stdout, &v["idx"], "pass", "");
            }
            "assert_return" | "action" => {
                let exec = &v["exec"];
                let field = exec["field"].as_str().unwrap_or("").to_string();
                let args = exec["args"].as_array().cloned().unwrap_or_default();
                let results = v["results"].clone();
                // Dispatch to the host for the current module index. Multi-
                // module scripts get per-index hosts generated by the runner.
                let outcome = match current_module {
                    0 => {
                        let h = host.get_or_insert_with(|| Host {
                            data: Default::default(),
                            externrefs: vec![],
                        });
                        with_host(h, &field, &args, &results)
                    }
                    other => with_host_n(other, &field, &args, &results),
                };
                match outcome {
                    Ok(msg) => answer(&mut stdout, &v["idx"], "pass", &msg),
                    Err((kind, msg)) => answer(&mut stdout, &v["idx"], &kind, &msg),
                }
            }
            "assert_trap" => {
                answer(&mut stdout, &v["idx"], "skip", "trap classification pending");
            }
            "assert_exhaustion" => {
                answer(&mut stdout, &v["idx"], "skip", "exhaustion pending");
            }
            "assert_unlinkable" => {
                answer(&mut stdout, &v["idx"], "skip", "linking pending");
            }
            "harness_skip_malformed" => {
                // Malformed-module assertions test the reference *decoder*,
                // not a compiled implementation: the module never reaches
                // wars. Counted as skipped, not pass/fail.
                answer(&mut stdout, &v["idx"], "skip",
                    "assert_malformed tests spec decoder, not implementation");
            }
            "harness_validate" => {
                answer(&mut stdout, &v["idx"], "skip",
                    "assert_invalid requires pre-codegen validation");
            }
            "harness_skip_invalid_module" => {
                answer(&mut stdout, &v["idx"], "skip",
                    "directive follows an invalid module (assert_invalid); not executed");
            }
            "register" => {
                answer(&mut stdout, &v["idx"], "skip", "register pending");
            }
            "done" => break,
            _ => {
                answer(&mut stdout, &v["idx"], "skip", "op not handled");
            }
        }
    }
}


/// Convert one JSON arg to a typed value.
fn arg_val<T: std::str::FromStr>(a: &serde_json::Value) -> Result<T, (String, String)> {
    // Numbers arrive as i64/u64/f64 bits; T is u32/u64/f32/f64 via FromStr on
    // a rendered decimal — but bits must pass exactly, so parse via u64.
    let v = a.get("v").and_then(|x| x.as_i64()).unwrap_or(0);
    v.to_string().parse::<T>().map_err(|_| {
        (
            "fail".to_string(),
            format!("cannot convert arg {}", a),
        )
    })
}

fn result_vec0<TL: Flatten>(tl: TL) -> Vec<u64> {
    // tuple_list types are right-nested tuples: (a, (b, ())). We flatten
    // scalars generically via a helper trait below.
    flatten(tl)
}

pub trait Flatten {
    fn flatten_into(self, out: &mut Vec<u64>);
}

impl Flatten for () {
    fn flatten_into(self, _out: &mut Vec<u64>) {}
}

macro_rules! flatten_tuple {
    ($($name:ident),+) => {
        impl<$($name: Into<u64> + Clone),+> Flatten for ($($name,)+) {
            fn flatten_into(self, out: &mut Vec<u64>) {
                #[allow(non_snake_case)]
                let ($($name,)+) = self;
                $(out.push($name.into());)+
            }
        }
    };
}

flatten_tuple!(A);
flatten_tuple!(A, B);
flatten_tuple!(A, B, C);
flatten_tuple!(A, B, C, D);
flatten_tuple!(A, B, C, D, E);
flatten_tuple!(A, B, C, D, E, F);

fn flatten<TL: Flatten>(tl: TL) -> Vec<u64> {
    let mut v = vec![];
    tl.flatten_into(&mut v);
    v
}

fn check_i32(got: &[u64], i: usize, results: &serde_json::Value) -> Result<String, (String, String)> {
    let want = results[0]["v"].as_i64().unwrap_or(0);
    let g = got.get(i).copied().unwrap_or(u64::MAX) as i64 as i32;
    if g as i64 == want {
        Ok(String::new())
    } else {
        Err(("fail".to_string(), format!("expected {want}, got {}", g)))
    }
}

fn check_i64(got: &[u64], i: usize, results: &serde_json::Value) -> Result<String, (String, String)> {
    let want = results[0]["v"].as_i64().unwrap_or(0);
    let g = got.get(i).copied().unwrap_or(u64::MAX) as i64;
    if g == want {
        Ok(String::new())
    } else {
        Err(("fail".to_string(), format!("expected {want}, got {g}")))
    }
}

fn check_f32(got: &[u64], i: usize, results: &serde_json::Value) -> Result<String, (String, String)> {
    let want_bits = results[0]["bits"].as_u64().unwrap_or(0) as u32;
    let nan = results[0]["nan"].as_str();
    let g = got.get(i).copied().unwrap_or(0) as u32;
    match nan {
        Some("canonical") => {
            if g & 0x7fff_ffff == 0x7fc0_0000 { Ok(String::new()) }
            else { Err(("fail".to_string(), format!("expected canonical NaN, got {g:#x}"))) }
        }
        Some("arithmetic") => {
            if g & 0x7fc0_0000 == 0x7fc0_0000 { Ok(String::new()) }
            else { Err(("fail".to_string(), format!("expected arithmetic NaN, got {g:#x}"))) }
        }
        _ => {
            if g == want_bits { Ok(String::new()) }
            else { Err(("fail".to_string(), format!("expected {want_bits:#x}, got {g:#x}"))) }
        }
    }
}

fn check_f64(got: &[u64], i: usize, results: &serde_json::Value) -> Result<String, (String, String)> {
    let want_bits = results[0]["bits"].as_u64().unwrap_or(0);
    let nan = results[0]["nan"].as_str();
    let g = got.get(i).copied().unwrap_or(0);
    match nan {
        Some("canonical") => {
            if g & 0x7fff_ffff_ffff_ffff == 0x7ff8_0000_0000_0000 { Ok(String::new()) }
            else { Err(("fail".to_string(), format!("expected canonical NaN, got {g:#x}"))) }
        }
        Some("arithmetic") => {
            if g & 0x7ff8_0000_0000_0000 == 0x7ff8_0000_0000_0000 { Ok(String::new()) }
            else { Err(("fail".to_string(), format!("expected arithmetic NaN, got {g:#x}"))) }
        }
        _ => {
            if g == want_bits { Ok(String::new()) }
            else { Err(("fail".to_string(), format!("expected {want_bits:#x}, got {g:#x}"))) }
        }
    }
}

/// Dispatch for modules >= 1: generated per-file `dispatch_mN!` macros.
fn with_host_n(
    module: usize,
    field: &str,
    args: &[serde_json::Value],
    results: &serde_json::Value,
) -> Result<String, (String, String)> {
    let _ = (module, field, args, results);
    Err(("skip".to_string(), "multi-module invoke not generated".to_string()))
}

fn with_host(
    h: &mut Host,
    field: &str,
    args: &[serde_json::Value],
    results: &serde_json::Value,
) -> Result<String, (String, String)> {
    invoke_export0(h, field, args, results)
}

/// Invoke an export of module 0 and compare against expected results.
/// `args`/`results` are the JSON arrays from the harness. The generated
/// per-file code supplies `dispatch_m0!` for the concrete module.
#[allow(unused_macros)]
macro_rules! dispatch_m0 {
    ($host:expr, $field:expr, $args:expr, $results:expr) => {
        Err(("skip".to_string(), "no exports".to_string()))
    };
}

fn invoke_export0(
    host: &mut Host,
    field: &str,
    args: &[serde_json::Value],
    results: &serde_json::Value,
) -> Result<String, (String, String)> {
    dispatch_m0!(host, field, args, results)
}
"##;
