[package]
name = "tester"
version = "0.1.0"
edition = "2021"

[dependencies]
wars = { path = "../wars", features = ["waffle", "wasmparser"] }
wars-rt = { path = "../wars-rt" }
anyhow = "1.0"
tuple_list = "0.1.3"
static_assertions = "1.1"

[build-dependencies]
wars = { path = "../wars", features = ["waffle", "wasmparser"] }
wasm-encoder = "0.240.0"
quote = "1.0"
proc-macro2 = "1.0"
syn = { version = "2.0", features = ["full"] }
anyhow = "1.0"
